backend:
  name: git-gateway
  branch: main

media_folder: "pdf"
public_folder: "/pdf"

collections:
  - name: "docs"
    label: "Documenti"
    folder: "_docs/determine"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "PDF", name: "pdf", widget: "file" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Determine", "Delibere", "Bandi"] }
